### ISSUE TITLE
 Could not initialize SDL video:

### ISSUE THREAD

**Issue by Throne-myworld** [glample/Arnold#17]
I tried to run it on linux(the wsl) but things turned to be complex:
Traceback (most recent call last):
  File "arnold.py", line 24, in <module>
    parse_game_args(remaining + ['--dump_path', dump_path])
  File "/mnt/d/yuan/Arnold-master/src/args.py", line 114, in parse_game_args
    module.main(parser, args)
  File "/mnt/d/yuan/Arnold-master/src/doom/scenarios/defend_the_center.py", line 90, in main
    evaluate_defend_the_center(game, network, params)
  File "/mnt/d/yuan/Arnold-master/src/doom/scenarios/defend_the_center.py", line 107, in evaluate_defend_the_center
    game.start(map_id=map_id, episode_time=params.episode_time, log_events=True)
  File "/mnt/d/yuan/Arnold-master/src/doom/game.py", line 491, in start
    self.game.init()
vizdoom.vizdoom.ViZDoomErrorException: Could not initialize SDL video:
No available video device

**Comment by ishwarinalgirkar** [comment]
Your WSL does not have its graphics enabled, you will have to allow your wsl to export display to windows and install an x server on windows
