### ISSUE TITLE
training in deathmatch

### ISSUE THREAD

**Issue by wwxFromTju** [glample/Arnold#2]
Hi, when I run "python arnold.py --scenario deathmatch --wad deathmatch_rockets --n_bots 8 \
--action_combinations "move_fb;move_lr;turn_lr;attack" --frame_skip 4 \
--game_features "enemy" --network_type dqn_rnn --recurrence lstm --n_rec_updates 5"

some error happen:
NFO [25900] - 04/19/18 18:46:51 - 0:00:00 - Input shape: (3, 60, 108)
INFO [25900] - 04/19/18 18:46:51 - 0:00:00 - Conv layer output dim : 4608
INFO [25900] - 04/19/18 18:46:51 - 0:00:00 - Hidden layer input dim: 4672
Traceback (most recent call last):
  File "arnold.py", line 24, in <module>
    parse_game_args(remaining + ['--dump_path', dump_path])
  File "/home/wwx/Arnold/src/args.py", line 114, in parse_game_args
    module.main(parser, args)
  File "/home/wwx/Arnold/src/doom/scenarios/deathmatch.py", line 110, in main
    network = get_model_class(params.network_type)(params)
  File "/home/wwx/Arnold/src/model/dqn/recurrent.py", line 62, in __init__
    super(DQNRecurrent, self).__init__(params)
  File "/home/wwx/Arnold/src/model/dqn/base.py", line 119, in __init__
    self.module.cuda()
  File "/home/wwx/anaconda3/envs/doom/lib/python3.5/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/wwx/anaconda3/envs/doom/lib/python3.5/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/wwx/anaconda3/envs/doom/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/wwx/anaconda3/envs/doom/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
    params = rnn.get_parameters(fn, handle, fn.weight_buf)
  File "/home/wwx/anaconda3/envs/doom/lib/python3.5/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError

**Comment by glample** [comment]
Mmm I'm not sure what is happening. Are you able to run the provided scenarios? Your training configurations looks fine.

**Comment by wwxFromTju** [comment]
other scenarios is fine, just this one have problem

**Comment by glample** [comment]
Mmm your command is running fine. I guess you are using a more recent version of PyTorch.. What version are you using? I'm using 0.3.0.post4

**Comment by wwxFromTju** [comment]
yep, fix it.
