### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by lz199144** [glample/Arnold#8]
```
Traceback (most recent call last):
  File "arnold.py", line 24, in <module>
    parse_game_args(remaining + ['--dump_path', dump_path])
  File "/home/ricardoliu/Arnold/src/args.py", line 114, in parse_game_args
    module.main(parser, args)
  File "/home/ricardoliu/Arnold/src/doom/scenarios/health_gathering.py", line 101, in main
    evaluate_health_gathering(game, network, params)
  File "/home/ricardoliu/Arnold/src/doom/scenarios/health_gathering.py", line 144, in evaluate_health_gathering
    action = network.next_action(last_states)
  File "/home/ricardoliu/Arnold/src/model/dqn/base.py", line 193, in next_action
    scores, pred_features = self.f_eval(last_states)
  File "/home/ricardoliu/Arnold/src/model/dqn/feedforward.py", line 51, in f_eval
    [variables[-1, i] for i in range(self.params.n_variables)]
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ricardoliu/Arnold/src/model/dqn/feedforward.py", line 27, in forward
    for x in x_variables)
AssertionError

```

**Comment by PygmalionChen** [comment]
I've got the same error.

**Comment by RozenAstrayChen** [comment]
me too

**Comment by sophiefsadler** [comment]
I solved this by rolling back my PyTorch version to 0.3.1

**Comment by biancini** [comment]
I think I fixed the assertion with the PR here: https://github.com/glample/Arnold/pull/10
Made it work with python3 and pytorch 1.3.1

**Comment by Throne-myworld** [comment]
File "D:\PyCharmproject\Arnold-master\Arnold-master\src\doom\game.py", line 133, in __init__
    assert os.path.isfile(self.scenario_path)
AssertionError
D:\PyCharmproject\Arnold-master\Arnold-master\resources\scenarios\.wad

can anyone solve this issue?
